version: '3'

services:
  backend:
    # image: nvidia/cuda:11.4.2-runtime-ubuntu20.04
    # image: tensorflow/tensorflow:latest-gpu
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/opt/server
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - 5000:5000

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
