version: '3'

services: 
  test: 
    # image: nvidia/cuda:11.4.2-runtime-ubuntu20.04
    # image: tensorflow/tensorflow:latest-gpu
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/opt/server
    # command: python3 -c "import tensorflow as tf;tf.test.gpu_device_name()"
    # command: python3 inception_resnet_v2_predict.py
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    # deploy: 
    #   resources: 
    #     reservations: 
    #       devices: 
    #       - driver: nvidia 
    #         count: 1 
    #         capabilities: [gpu, utility]